checks:
    javascript: true
    
filter:
    excluded_paths:
        - test/*
        - node_modules/*

build:
    dependencies:
        override:
            - npm install
            
    tests:
        override:
            -
                command: "npm run unit-clover"
                coverage:
                    file: "build/coverage/clover.xml"
                    format: "clover"
